[metadata]
# This includes the license file(s) in the wheel.
# https://wheel.readthedocs.io/en/stable/user_guide.html#including-license-files-in-the-generated-wheel-file
license_files = LICENSE

[flake8]
max-line-length = 120

[sdist_dsc]
# Force the version to use `~` before any prerelease identifiers
forced-upstream-version = 3.6.0-rc.2.post1
