# This workflow will upload a Python Package using Twine when a release is created

# See https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
# Also see https://github.com/marketplace/actions/pypi-publish

name: Build Debian package 📦

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-deb:
    name: Build Debian package 📦
    runs-on: ubuntu-latest
    container:
      image: debian:12
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Install system packages
      run: |
        apt-get update
        apt-get install -y python3.11 python3-pip python3-venv dpkg-dev debhelper dh-python build-essential python3-all git
    - name: Set up virtual environment
      run: |
        python3 -m venv /opt/venv
        . /opt/venv/bin/activate
    - name: Install dependencies
      run: |
        . /opt/venv/bin/activate
        python3 -m pip install --upgrade pip
        pip3 install setuptools
        pip3 install git+https://github.com/AndyEveritt/stdeb.git
        pip3 install python-dateutil
        pip3 install wheel
    - name: Clean up previous builds
      run: rm -rf deb_dist/ || true
    - name: Build Debian package
      run: |
        . /opt/venv/bin/activate
        make build_deb || exit 1
    - name: List built packages
      run: find deb_dist -name "*.deb"
    - name: Upload Debian package to release
      uses: softprops/action-gh-release@v2
      with:
        token: ${{ secrets.PAT }}
        files: "deb_dist/*.deb"
        tag_name: ${{ github.event.release.tag_name }}
